import copy
import ctypes
from pathlib import Path
import struct
import unittest
import tempfile
import subprocess
import sys
import json
from patchlab.patch import apply,inspect,make_manifest,rollback
from patchlab.pe import PEImage


class PatchTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.baseline=Path('build/strategy_baseline.exe').read_bytes()
        cls.manifest=make_manifest(cls.baseline)
        cls.patched,cls.receipt=apply(cls.baseline,cls.manifest)

    def test_instruction_patch_and_mapping(self):
        old,new=inspect(self.baseline),inspect(self.patched)
        self.assertEqual(old['gate']['features'],0); self.assertEqual(new['gate']['features'],15)
        self.assertEqual(new['gate']['virtual_address'],new['image_base']+new['gate']['rva'])

    def test_only_allowlisted_bytes_change(self):
        offset=self.manifest['file_offset']; checksum=PEImage(self.baseline).checksum_offset
        allowed=set(range(offset,offset+6))|set(range(checksum,checksum+4))
        changes={i for i,(a,b) in enumerate(zip(self.baseline,self.patched)) if a!=b}
        self.assertTrue(changes and changes<=allowed)
        for name in ('.text','.cal','.rdata','.pdata'):
            s=PEImage(self.baseline).section(name); start,end=s['raw_offset'],s['raw_offset']+s['raw_size']
            self.assertEqual(self.baseline[start:end],self.patched[start:end])

    def test_native_windows_checksum_oracle(self):
        dll=ctypes.WinDLL('imagehlp')
        function=dll.CheckSumMappedFile
        function.argtypes=[ctypes.c_void_p,ctypes.c_uint32,ctypes.POINTER(ctypes.c_uint32),ctypes.POINTER(ctypes.c_uint32)]
        function.restype=ctypes.c_void_p
        for data in (self.baseline,self.patched,self.patched+b'x'):
            buffer=ctypes.create_string_buffer(data)
            header,total=ctypes.c_uint32(),ctypes.c_uint32()
            self.assertTrue(function(buffer,len(data),ctypes.byref(header),ctypes.byref(total)))
            self.assertEqual(total.value,PEImage(data).checksum())

    def test_exact_rollback(self):
        self.assertEqual(rollback(self.patched,self.receipt),self.baseline)

    def test_wrong_binary_and_double_apply(self):
        changed=bytearray(self.baseline); changed[-1]^=1
        for data in (changed,self.patched):
            with self.assertRaises(ValueError): apply(data,self.manifest)

    def test_disallowed_manifest_edits(self):
        for key,value in [('file_offset',0),('replacement_bytes','909090909090'),('expected_bytes','00'),('schema_version',True)]:
            m=copy.deepcopy(self.manifest); m[key]=value
            with self.assertRaises(ValueError): apply(self.baseline,m)

    def test_bad_receipt(self):
        r=copy.deepcopy(self.receipt); r['original_checksum_bytes']='00000000'
        with self.assertRaises(ValueError): rollback(self.patched,r)
        with self.assertRaises(ValueError): rollback(self.baseline,self.receipt)

    def test_truncated_and_wrong_format(self):
        for data in (b'',bytes(300),self.baseline[:64],self.baseline[:1024]):
            with self.assertRaises(ValueError): PEImage(data)
        data=bytearray(self.baseline); pe=struct.unpack_from('<I',data,0x3c)[0]
        struct.pack_into('<H',data,pe+4,0x14c)
        with self.assertRaises(ValueError): PEImage(data)

    def test_signed_image_rejected(self):
        data=bytearray(self.baseline); pe=struct.unpack_from('<I',data,0x3c)[0]
        struct.pack_into('<II',data,pe+24+112+32,256,32)
        with self.assertRaises(ValueError): PEImage(data)

    def test_calibration_extracted_from_binary(self):
        cal=inspect(self.baseline)['calibration']
        self.assertEqual(cal['rpm_axis'],[1000,3000,6000])
        self.assertEqual(cal['torque_maps'][2],[0,130,260,0,175,350,0,150,300])

    def test_cli_patch_rollback_and_no_overwrite(self):
        with tempfile.TemporaryDirectory() as directory:
            root=Path(directory)
            manifest=root/'manifest.json'; candidate=root/'candidate.exe'; receipt=root/'receipt.json'; restored=root/'restored.exe'
            # Accept BOM-tagged UTF-16 as generated by Windows PowerShell 5 redirection.
            manifest.write_bytes(json.dumps(self.manifest).encode('utf-16'))
            cmd=[sys.executable,'-m','patchlab','apply','build/strategy_baseline.exe',str(manifest),str(candidate)]
            result=subprocess.run(cmd,capture_output=True,text=True)
            self.assertEqual(result.returncode,0,result.stderr)
            self.assertEqual(candidate.read_bytes(),self.patched)
            receipt.write_bytes(result.stdout.encode('utf-16'))
            second=subprocess.run(cmd,capture_output=True,text=True)
            self.assertEqual(second.returncode,2)
            result=subprocess.run([sys.executable,'-m','patchlab','rollback',str(candidate),str(receipt),str(restored)],capture_output=True,text=True)
            self.assertEqual(result.returncode,0,result.stderr)
            self.assertEqual(restored.read_bytes(),self.baseline)


if __name__=='__main__': unittest.main()
